var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,c){a.raw=c;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};
$jscomp.polyfill=function(a,c,b,f){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,f):$jscomp.polyfillUnisolated(a,c,b,f))};$jscomp.polyfillUnisolated=function(a,c,b,f){b=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var e=a[f];if(!(e in b))return;b=b[e]}a=a[a.length-1];f=b[a];c=c(f);c!=f&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,f){var e=a.split(".");a=1===e.length;f=e[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var d=e[g];if(!(d in f))return;f=f[d]}e=e[e.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?f[e]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==b&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(f,e,{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Object.is",function(a){return a?a:function(c,b){return c===b?0!==c||1/c===1/b:c!==c&&b!==b}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(c,b){var f=this;f instanceof String&&(f=String(f));var e=f.length;b=b||0;for(0>b&&(b=Math.max(b+e,0));b<e;b++){var g=f[b];if(g===c||Object.is(g,c))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(c,b){return-1!==$jscomp.checkStringArgs(this,c,"includes").indexOf(c,b||0)}},"es6","es3");
var HoloVideoObject=function(a,c){this.id=HoloVideoObject._instanceCounter++;this.state=HoloVideoObject.States.Empty;this.suspended=!1;this.gl=a;this.audioVolume=this.logLevel=1;c?(this.createOptions=c,2>c.numAsyncFrames&&(this._logWarning("numAsyncFrames must be at least 2 ("+c.numAsyncFrames+" specified)"),this.createOptions.numAsyncFrames=2)):this.createOptions={};this.createOptions.numAsyncFrames||(this.createOptions.numAsyncFrames=3);document.addEventListener("visibilitychange",function(){document.hidden?
(this.wasPlaying=this.state==HoloVideoObject.States.Playing,this._logInfo("document hidden -> pausing playback"),this.pause()):this.wasPlaying&&(this.wasPlaying=!1,this._logInfo("document visible -> resuming playback"),this.play())}.bind(this));c=a.canvas;c.addEventListener("webglcontextlost",function(b){this.contextLost=!0;this.wasPlaying=this.state==HoloVideoObject.States.Playing;this.pause();this._logInfo("webglcontextlost -> pausing playback");this._releaseWebGLResources(a)}.bind(this),!1);c.addEventListener("webglcontextrestored",
function(b){this._initializeWebGLResources(this.gl);if(this.json&&this.outputBuffers){b=this.json.extensions[HoloVideoObject._extName];for(var f=this.gl,e=f.getParameter(f.ARRAY_BUFFER_BINDING),g=0;3>g;++g)f.bindBuffer(f.ARRAY_BUFFER,this.outputBuffers[g]),f.bufferData(f.ARRAY_BUFFER,12*b.maxVertexCount,f.STREAM_COPY);f.bindBuffer(f.ARRAY_BUFFER,e)}this.contextLost=!1;this.wasPlaying&&(this.wasPlaying=!1,this._logInfo("webglcontextrestored -> resuming playback"),this.play())}.bind(this),!1);console.log("HoloVideoObject version "+
HoloVideoObject.Version.String);this._initializeWebGLResources(a)};
HoloVideoObject.prototype._createProgram=function(a,c,b,f){function e(d,k,m){m=d.createShader(m);d.shaderSource(m,k);d.compileShader(m);return m}var g=a.createProgram();c=e(a,c,a.VERTEX_SHADER);a.attachShader(g,c);a.deleteShader(c);b=e(a,b,a.FRAGMENT_SHADER);a.attachShader(g,b);a.deleteShader(b);f&&f(g);a.linkProgram(g);(f=a.getProgramInfoLog(g))&&this._logError(f);(f=a.getShaderInfoLog(c))&&this._logError(f);(f=a.getShaderInfoLog(b))&&this._logError(f);return g};
HoloVideoObject.prototype._loadJSON=function(a,c){var b=new XMLHttpRequest;b.overrideMimeType("application/json");b.open("GET",a,!0);b.onreadystatechange=function(){4==b.readyState&&"200"==b.status&&c(b.responseText,this)};b.send(null);return b.responseText};
HoloVideoObject.prototype._loadArrayBuffer=function(a,c){var b=new XMLHttpRequest;b.name=a.substring(a.lastIndexOf("/")+1,a.length);b.responseType="arraybuffer";b.onprogress=function(f){f.lengthComputable&&this._logInfo(b.name+" progress: "+Math.floor(f.loaded/f.total*100))}.bind(this);b.onreadystatechange=function(){if(4==b.readyState){if("200"==b.status){var f=b.response;f&&c&&c(f)}else this._logInfo("_loadArrayBuffer status = "+b.status);this.httpRequest==b&&(this.httpRequest=null)}}.bind(this);
b.ontimeout=function(){this._logInfo("_loadArrayBuffer timeout")};b.open("GET",a,!0);b.send(null);this.httpRequest=b};
HoloVideoObject.prototype._startPlaybackIfReady=function(){this.state==HoloVideoObject.States.Opening&&this.buffersLoaded>=this.minBuffers&&this.videosLoaded>=this.minVideos&&(this._logInfo("state -> Opened"),this.state=HoloVideoObject.States.Opened,this.openOptions.autoplay&&this.play());if(this.suspended){var a=this.json.extensions[HoloVideoObject._extName].timeline;a=this.json.images[a[this.currentVideoIndex].image];a=a.video;!a.paused&&a.playing||!a.preloaded||(this._logInfo("video "+a.mp4Name+
" was suspended, resuming"),this.suspended=!1,a.play())}else this.state==HoloVideoObject.States.Playing&&(a=this.json.extensions[HoloVideoObject._extName].timeline,a=this.json.images[a[this.currentVideoIndex].image],a=a.video,a.playing||a.play())};
HoloVideoObject.prototype._loadNextBuffer=function(){if(0==this.freeArrayBuffers.length)this._logInfo("_loadNextBuffer no free buffer slot available");else{var a=this.nextBufferLoadIndex;this.nextBufferLoadIndex=(this.nextBufferLoadIndex+1)%this.json.buffers.length;this.fallbackFrameBuffer&&0==this.nextBufferLoadIndex&&(this.nextBufferLoadIndex=1);var c=this.json.buffers[a],b=this.urlRoot+c.uri;c.loaded=!1;var f=-1;0==a?this._logInfo("loading preview frame buffer"):(f=this.freeArrayBuffers.shift(),
this._logInfo("loading buffer: "+c.uri+" into slot "+f));this.pendingBufferDownload=!0;this._loadArrayBuffer(b,function(e){this._logInfo("buffer loaded: "+c.uri);this.fallbackFrameBuffer||this.filledFallbackFrame?(++this.buffersLoaded,this.buffers[f]=e,e.bufferIndex=a,c.arrayBufferIndex=f,c.loaded=!0,this.needMeshData=this.pendingBufferDownload=!1,this._startPlaybackIfReady(),this._loadNextBuffer()):(this._logInfo("fallback frame buffer downloaded "+c.uri),this.fallbackFrameBuffer=e,this._loadNextBuffer(),
this.pendingBufferDownload=!1)}.bind(this))}};
HoloVideoObject.prototype._loadNextVideo=function(){if(0!=this.freeVideoElements.length){var a=this.freeVideoElements.shift(),c=this.videoElements[a];c.videoElementIndex=a;a=this.nextVideoLoadIndex;var b=this.json.extensions[HoloVideoObject._extName].timeline.length;this.nextVideoLoadIndex=(this.nextVideoLoadIndex+1)%b;a=this.json.images[this.json.extensions[HoloVideoObject._extName].timeline[a].image];a.video=c;c.preloaded=!1;c.autoplay=!1;c.muted=this.openOptions.autoplay||!this.openOptions.audioEnabled;
this.isSafari&&(c.muted=!0);c.loop=1==b&&this.openOptions.autoloop;c.preload="auto";c.crossOrigin="use-credentials";c.playing=!1;c.preloaded=!1;a.uri.split(".").pop();b=a.extensions[HoloVideoObject._extName];void 0===this.openOptions.streamMode&&(this.openOptions.streamMode=HoloVideoObject.StreamMode.Automatic);if(this.openOptions.streamMode==HoloVideoObject.StreamMode.HLS||this.openOptions.streamMode==HoloVideoObject.StreamMode.Automatic&&this.isSafari&&b.hlsUri&&(!this.iOSVersion||14>this.iOSVersion.major))c.src=
this.urlRoot+b.hlsUri,c.mp4Name=b.hlsUri;else if(this.openOptions.streamMode==HoloVideoObject.StreamMode.Dash||this.openOptions.streamMode==HoloVideoObject.StreamMode.Automatic&&!this.isSafari&&b.dashUri&&"undefined"!=typeof dashjs){this.dashPlayer||(this.dashPlayer=dashjs.MediaPlayer().create(),this.dashPlayer.initialize());var f=this.urlRoot+b.dashUri;this.dashPlayer.attachView(c);this.dashPlayer.attachSource(f);c.mp4Name=b.dashUri}else f=this.urlRoot+a.uri,c.src=f,c.mp4Name=a.uri;this._logInfo("loading video "+
c.mp4Name);var e=this;c.addEventListener("canplay",function(){e.videoState=HoloVideoObject.VideoStates.CanPlay});c.addEventListener("play",function(){e.videoState=HoloVideoObject.VideoStates.Playing});c.addEventListener("canplaythrough",function(){e.videoState=HoloVideoObject.VideoStates.CanPlayThrough});c.addEventListener("waiting",function(){e.videoState=HoloVideoObject.VideoStates.Waiting});c.addEventListener("suspend",function(){e.videoState=HoloVideoObject.VideoStates.Suspended});c.addEventListener("stalled",
function(){e.videoState=HoloVideoObject.VideoStates.Stalled});c.canplay=function(){this._logInfo("video -> canplay");this.videoState=HoloVideoObject.VideoStates.CanPlay}.bind(this);c.canplaythrough=function(){this._logInfo("video -> canplaythrough");this.videoState=HoloVideoObject.VideoStates.CanPlayThrough}.bind(this);c.waiting=function(){this._logInfo("video -> waiting");this.videoState=HoloVideoObject.VideoStates.Waiting}.bind(this);c.suspend=function(){this._logInfo("video -> suspend");this.videoState=
HoloVideoObject.VideoStates.Suspended}.bind(this);c.stalled=function(){this._logInfo("video -> stalled");this.videoState=HoloVideoObject.VideoStates.Stalled}.bind(this);c.onerror=function(g){this._logInfo("video error: "+g.target.error.code+" - "+g.target.mp4Name)}.bind(this);c.onended=function(){c.playing=!1;this._onVideoEnded(c)}.bind(this);this.isSafari?c.onplaying=function(){c.pause();c.muted=this.openOptions.autoplay||!this.openOptions.audioEnabled;c.preloaded=!0;this._logInfo("video loaded: "+
c.mp4Name);c.onplaying=function(){this._logInfo("video playing: "+c.mp4Name);c.playing=!0}.bind(this);++this.videosLoaded;this._startPlaybackIfReady();this._loadNextVideo()}.bind(this):(c.onloadeddata=function(){var g=c.play();void 0!==g&&g.then(function(d){}).catch(function(d){c.onplaying()})}.bind(this),c.onplaying=function(){c.pause();c.preloaded=!0;this._logInfo("video loaded: "+c.mp4Name);c.onplaying=function(){this._logInfo("video playing: "+c.mp4Name);c.playing=!0}.bind(this);++this.videosLoaded;
this._startPlaybackIfReady();this._loadNextVideo()}.bind(this));this.isSafari&&c.play()}};
HoloVideoObject.prototype.rewind=function(){if(this.json){this._logInfo("rewind");var a=this.json.images[this.json.extensions[HoloVideoObject._extName].timeline[this.currentVideoIndex].image].video;a.pause();a.playing=!1;a.currentTime=0;this.state=HoloVideoObject.States.Opening;this.freeArrayBuffers=[];for(a=0;a<Math.min(this.openOptions.maxBuffers,this.json.buffers.length-1);++a)this.freeArrayBuffers.push(a);this.currentBufferIndex=0;this.nextBufferLoadIndex=this.fallbackFrameBuffer?1:0;this.lastKeyframe=
this.frameIndex=-1;this.nextPbo=0;this.lastVideoSampleIndex=-1;this.filledFallbackFrame=!1;this.prevPrevMesh=this.prevMesh=this.curMesh=null;if(this.readFences)for(a=0;a<this.readFences.length;++a)this.readFences[a]&&(this.gl.deleteSync(this.readFences[a]),this.readFences[a]=null);this._loadNextBuffer();this._loadFallbackFrame()}};
HoloVideoObject.prototype.forceLoad=function(){var a=this;if(this.json){var c=this.json.images[this.json.extensions[HoloVideoObject._extName].timeline[this.currentVideoIndex].image].video;c.playing?this._logInfo("forceLoad: video already playing"):c.preloaded||(this._logInfo("forceLoad: manually starting video"),this.suspended=!0,c=c.play(),void 0!==c&&c.then(function(b){a.state=HoloVideoObject.States.Playing}).catch(function(b){a._logInfo("play prevented: "+b)}))}else this._logInfo("forceLoad: don't have json yet")};
HoloVideoObject.prototype._onVideoEnded=function(a){this._logInfo("video ended = "+a.mp4Name);this.freeVideoElements.push(a.videoElementIndex);a.videoElementIndex=-1;a=this.json.extensions[HoloVideoObject._extName].timeline;if(this.currentVideoIndex!=a.length-1||this.openOptions.autoloop)this.currentVideoIndex=(this.currentVideoIndex+1)%a.length,this._loadNextVideo(),this._startPlaybackIfReady();else if(this.eos=!0,this.onEndOfStream)this.onEndOfStream(this)};
HoloVideoObject.prototype._setupTransformFeedback=function(){var a=this.gl;this.outputBufferIndex=0;this.deltasBuf=a.createBuffer();this.outputBuffers=[a.createBuffer(),a.createBuffer(),a.createBuffer()];this.transformFeedbacks=[a.createTransformFeedback(),a.createTransformFeedback(),a.createTransformFeedback()];this.vaos=[a.createVertexArray(),a.createVertexArray(),a.createVertexArray()];a.bindVertexArray(null);for(var c=0;3>c;++c)a.bindTransformFeedback(a.TRANSFORM_FEEDBACK,this.transformFeedbacks[c]),
a.bindBufferBase(a.TRANSFORM_FEEDBACK_BUFFER,0,this.outputBuffers[c]);this.normalsVao=a.createVertexArray();this.normalsTF=a.createTransformFeedback();a.bindTransformFeedback(a.TRANSFORM_FEEDBACK,null);a.bindBuffer(a.TRANSFORM_FEEDBACK_BUFFER,null);c=this._createProgram(a,"#version 300 es\n            in vec3 inQuantized;\n            in vec3 prevPos;\n            in vec3 prevPrevPos;\n\n            uniform vec3 decodeMin;\n            uniform vec3 decodeMax;\n            uniform int havePrevPos;\n            uniform int havePrevPrevPos;\n\n            out vec3 outPos;\n\n            void main()\n            {\n                if (havePrevPos == 1)\n                {\n                    vec3 dm = vec3(0.0, 0.0, 0.0);\n\n                    if (havePrevPrevPos == 1)\n                    {\n                        dm = prevPos - prevPrevPos;\n                    }\n\n                    vec3 delta = (decodeMax - decodeMin) * inQuantized + decodeMin;\n                    outPos = prevPos + dm + delta;\n                }\n\n                else\n                {\n                    outPos = (decodeMax - decodeMin) * inQuantized + decodeMin;\n                }\n            }",
"#version 300 es\n            out lowp vec4 fragColor;\n            void main()\n            {\n                fragColor = vec4(0,0,0,0);\n            }\n            ",function(b){a.transformFeedbackVaryings(b,["outPos"],a.SEPARATE_ATTRIBS)});c.havePrevPosLoc=a.getUniformLocation(c,"havePrevPos");c.havePrevPrevPosLoc=a.getUniformLocation(c,"havePrevPrevPos");c.decodeMinLoc=a.getUniformLocation(c,"decodeMin");c.decodeMaxLoc=a.getUniformLocation(c,"decodeMax");c.inQuantizedLoc=a.getAttribLocation(c,
"inQuantized");c.prevPosLoc=a.getAttribLocation(c,"prevPos");c.prevPrevPosLoc=a.getAttribLocation(c,"prevPrevPos");this.tfShader=c;c=this._createProgram(a,"#version 300 es\n            in vec2 inOctNormal;\n            out vec3 outNormal;\n\n            vec3 OctDecode(vec2 f)\n            {\n                f = f * 2.0 - 1.0;\n\n                // https://twitter.com/Stubbesaurus/status/937994790553227264\n                vec3 n = vec3( f.x, f.y, 1.0 - abs(f.x) - abs(f.y));\n                float t = clamp(-n.z, 0.0, 1.0);\n                n.x += n.x >= 0.0 ? -t : t;\n                n.y += n.y >= 0.0 ? -t : t;\n                return normalize(n);\n            }\n\n            void main()\n            {\n                outNormal = OctDecode(inOctNormal);\n            }",
"#version 300 es\n            out lowp vec4 fragColor;\n            void main()\n            {\n                fragColor = vec4(0,0,0,0);\n            }\n            ",function(b){a.transformFeedbackVaryings(b,["outNormal"],a.SEPARATE_ATTRIBS)});c.inOctNormalLoc=a.getAttribLocation(c,"inOctNormal");this.octNormalsShader=c};
HoloVideoObject.prototype._updateMeshTF=function(a,c,b,f,e,g){var d=this.gl;a.outputBuffer=this.outputBuffers[this.outputBufferIndex];var k=d.getParameter(d.ARRAY_BUFFER_BINDING),m=d.getParameter(d.ELEMENT_ARRAY_BUFFER_BINDING),n=d.getParameter(d.CURRENT_PROGRAM),h=d.getParameter(d.VERTEX_ARRAY_BINDING);d.useProgram(this.tfShader);d.bindBuffer(d.ARRAY_BUFFER,null);var l=this.tfShader;if(a.primitives[0].extensions[HoloVideoObject._extName].attributes.POSITION){this.lastKeyframe=this.frameIndex;d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,
f);d.bufferData(d.ELEMENT_ARRAY_BUFFER,g.indices,d.STATIC_DRAW);d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,m);d.bindBuffer(d.ARRAY_BUFFER,b);d.bufferData(d.ARRAY_BUFFER,g.compressedUVs,d.STATIC_DRAW);d.bindVertexArray(this.vaos[0]);this.prevPrevMesh=this.prevMesh=null;b=a.compressedPos.count;a.indexCount=a.indices.count;d.bindBuffer(d.ARRAY_BUFFER,this.deltasBuf);d.bufferData(d.ARRAY_BUFFER,g.compressedPos,d.DYNAMIC_DRAW);d.enableVertexAttribArray(l.inQuantizedLoc);d.vertexAttribPointer(l.inQuantizedLoc,
3,a.compressedPos.componentType,!0,0,0);d.disableVertexAttribArray(l.prevPosLoc);d.disableVertexAttribArray(l.prevPrevPosLoc);f=a.compressedPos.extensions[HoloVideoObject._extName].decodeMin;var p=a.compressedPos.extensions[HoloVideoObject._extName].decodeMax;d.uniform3fv(l.decodeMinLoc,f);d.uniform3fv(l.decodeMaxLoc,p);this.currentFrameInfo.bboxMin=f;this.currentFrameInfo.bboxMax=p;d.uniform1i(l.havePrevPosLoc,0);d.uniform1i(l.havePrevPrevPosLoc,0)}else b=a.deltas.count,a.indexCount=this.prevMesh.indexCount,
null==this.prevPrevMesh?d.bindVertexArray(this.vaos[1]):d.bindVertexArray(this.vaos[2]),d.bindBuffer(d.ARRAY_BUFFER,this.deltasBuf),d.bufferData(d.ARRAY_BUFFER,g.deltas,d.DYNAMIC_DRAW),d.enableVertexAttribArray(l.inQuantizedLoc),d.vertexAttribPointer(l.inQuantizedLoc,3,a.deltas.componentType,!0,0,0),d.uniform3fv(l.decodeMinLoc,a.deltas.extensions[HoloVideoObject._extName].decodeMin),d.uniform3fv(l.decodeMaxLoc,a.deltas.extensions[HoloVideoObject._extName].decodeMax),d.uniform1i(l.havePrevPosLoc,1),
d.bindBuffer(d.ARRAY_BUFFER,this.prevMesh.outputBuffer),d.enableVertexAttribArray(l.prevPosLoc),d.vertexAttribPointer(l.prevPosLoc,3,d.FLOAT,!1,0,0),null==this.prevPrevMesh?(d.uniform1i(l.havePrevPrevPosLoc,0),d.disableVertexAttribArray(l.prevPrevPosLoc)):(d.uniform1i(l.havePrevPrevPosLoc,1),d.bindBuffer(d.ARRAY_BUFFER,this.prevPrevMesh.outputBuffer),d.enableVertexAttribArray(l.prevPrevPosLoc),d.vertexAttribPointer(l.prevPrevPosLoc,3,d.FLOAT,!1,0,0));l=12*b;d.bindBuffer(d.ARRAY_BUFFER,a.outputBuffer);
d.bindBuffer(d.ARRAY_BUFFER,null);d.bindTransformFeedback(d.TRANSFORM_FEEDBACK,this.transformFeedbacks[this.outputBufferIndex]);d.enable(d.RASTERIZER_DISCARD);d.beginTransformFeedback(d.POINTS);d.drawArrays(d.POINTS,0,b);d.endTransformFeedback();d.disable(d.RASTERIZER_DISCARD);d.bindTransformFeedback(d.TRANSFORM_FEEDBACK,null);d.bindBuffer(d.TRANSFORM_FEEDBACK_BUFFER,null);d.bindBuffer(d.COPY_READ_BUFFER,a.outputBuffer);d.bindBuffer(d.COPY_WRITE_BUFFER,c);d.bufferData(d.COPY_WRITE_BUFFER,l,d.DYNAMIC_COPY);
d.copyBufferSubData(d.COPY_READ_BUFFER,d.COPY_WRITE_BUFFER,0,0,l);d.bindBuffer(d.COPY_READ_BUFFER,null);d.bindBuffer(d.COPY_WRITE_BUFFER,null);this.outputBufferIndex=(this.outputBufferIndex+1)%3;e&&g.compressedNormals&&(this.fileInfo.octEncodedNormals?(d.useProgram(this.octNormalsShader),d.bindBuffer(d.ARRAY_BUFFER,null),d.bindVertexArray(this.normalsVao),d.bindBuffer(d.ARRAY_BUFFER,this.deltasBuf),d.bufferData(d.ARRAY_BUFFER,g.compressedNormals,d.DYNAMIC_DRAW),d.enableVertexAttribArray(this.octNormalsShader.inOctNormalLoc),
d.vertexAttribPointer(this.octNormalsShader.inOctNormalLoc,2,d.UNSIGNED_BYTE,!0,0,0),l=12*b,d.bindBuffer(d.ARRAY_BUFFER,e),d.bufferData(d.ARRAY_BUFFER,l,d.DYNAMIC_DRAW),d.bindBuffer(d.ARRAY_BUFFER,null),d.bindTransformFeedback(d.TRANSFORM_FEEDBACK,this.normalsTF),d.bindBufferBase(d.TRANSFORM_FEEDBACK_BUFFER,0,e),d.enable(d.RASTERIZER_DISCARD),d.beginTransformFeedback(d.POINTS),d.drawArrays(d.POINTS,0,b),d.endTransformFeedback(),d.disable(d.RASTERIZER_DISCARD),d.bindTransformFeedback(d.TRANSFORM_FEEDBACK,
null),d.bindBuffer(d.TRANSFORM_FEEDBACK_BUFFER,null)):(d.bindBuffer(d.ARRAY_BUFFER,e),d.bufferData(d.ARRAY_BUFFER,g.compressedNormals,d.DYNAMIC_DRAW)));d.useProgram(n);d.bindBuffer(d.ARRAY_BUFFER,k);d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,m);d.bindVertexArray(h);return!0};
HoloVideoObject.prototype._updateMesh=function(a,c,b,f){this.frameIndex=(this.frameIndex+1)%this.meshFrames.length;var e=this.meshFrames[this.frameIndex];if(!e.ensureBuffers())return!1;this.prevPrevMesh&&(this.prevPrevMesh.uncompressedPos=null);this.prevPrevMesh=this.prevMesh;this.prevMesh=this.curMesh;this.curMesh=e;var g={indices:null,compressedPos:null,compressedUVs:null,compressedNormals:null,deltas:null},d=this.json.buffers,k=this.json.bufferViews;if(e.primitives[0].extensions[HoloVideoObject._extName].attributes.POSITION){var m=
d[k[e.indices.bufferView].buffer].arrayBufferIndex;var n=this.buffers[m],h=this.buffers[m];g.indices=new Uint16Array(this.buffers[m],k[e.indices.bufferView].byteOffset+e.indices.byteOffset,e.indices.count);g.compressedPos=new Uint16Array(n,k[e.compressedPos.bufferView].byteOffset+e.compressedPos.byteOffset,3*e.compressedPos.count);g.compressedUVs=new Uint16Array(h,k[e.compressedUVs.bufferView].byteOffset+e.compressedUVs.byteOffset,2*e.compressedUVs.count)}else m=d[k[e.deltas.bufferView].buffer].arrayBufferIndex,
g.deltas=new Uint8Array(this.buffers[m],k[e.deltas.bufferView].byteOffset+e.deltas.byteOffset,3*e.deltas.count);m!=this.currentBufferIndex&&(this._logInfo("currentBufferIndex -> "+m),this.freeArrayBuffers.push(this.currentBufferIndex),this.currentBufferIndex=m,this.pendingBufferDownload||this._loadNextBuffer());null!=e.compressedNormals&&(d=this.buffers[d[k[e.compressedNormals.bufferView].buffer].arrayBufferIndex],"VEC2"==e.compressedNormals.type?g.compressedNormals=new Uint8Array(d,k[e.compressedNormals.bufferView].byteOffset+
e.compressedNormals.byteOffset,2*e.compressedNormals.count):"VEC3"==e.compressedNormals.type&&(g.compressedNormals=new Uint16Array(d,k[e.compressedNormals.bufferView].byteOffset+e.compressedNormals.byteOffset,3*e.compressedNormals.count)));if(this.caps.webgl2&&!this.caps.badTF)return this._updateMeshTF(e,a,c,b,f,g);k=this.gl;d=k.getParameter(k.ARRAY_BUFFER_BINDING);m=k.getParameter(k.ELEMENT_ARRAY_BUFFER_BINDING);if(e.primitives[0].extensions[HoloVideoObject._extName].attributes.POSITION){this.lastKeyframe=
this.frameIndex;this.prevMesh&&(this.prevMesh=this.prevMesh.uncompressedPos=null);this.prevPrevMesh&&(this.prevPrevMesh=this.prevPrevMesh.uncompressedPos=null);k.bindBuffer(k.ELEMENT_ARRAY_BUFFER,b);k.bufferData(k.ELEMENT_ARRAY_BUFFER,g.indices,k.DYNAMIC_DRAW);e.indexCount=e.indices.count;b=e.compressedPos.count;e.uncompressedPos=new Float32Array(3*b);var l=e.compressedPos.extensions[HoloVideoObject._extName].decodeMin;n=e.compressedPos.extensions[HoloVideoObject._extName].decodeMax;this.currentFrameInfo.bboxMin=
l;this.currentFrameInfo.bboxMax=n;var p=(n[0]-l[0])/65535,u=(n[1]-l[1])/65535,r=(n[2]-l[2])/65535;for(n=0;n<b;++n){var q=3*n,t=q+1,v=q+2;e.uncompressedPos[q]=g.compressedPos[q]*p+l[0];e.uncompressedPos[t]=g.compressedPos[t]*u+l[1];e.uncompressedPos[v]=g.compressedPos[v]*r+l[2]}k.bindBuffer(k.ARRAY_BUFFER,a);k.bufferData(k.ARRAY_BUFFER,e.uncompressedPos,k.DYNAMIC_DRAW);k.bindBuffer(k.ARRAY_BUFFER,c);k.bufferData(k.ARRAY_BUFFER,g.compressedUVs,k.DYNAMIC_DRAW)}else{b=e.deltas.count;e.uncompressedPos=
new Float32Array(3*b);e.indexCount=this.prevMesh.indexCount;l=e.deltas.extensions[HoloVideoObject._extName].decodeMin;n=e.deltas.extensions[HoloVideoObject._extName].decodeMax;p=(n[0]-l[0])/255;u=(n[1]-l[1])/255;r=(n[2]-l[2])/255;var x=g.deltas;if(null==this.prevPrevMesh)for(n=0;n<b;++n){q=3*n;t=q+1;v=q+2;c=this.prevMesh.uncompressedPos[q];h=this.prevMesh.uncompressedPos[t];var w=this.prevMesh.uncompressedPos[v],y=x[q]*p+l[0],z=x[t]*u+l[1],A=x[v]*r+l[2];c+=y;h+=z;w+=A;e.uncompressedPos[q]=c;e.uncompressedPos[t]=
h;e.uncompressedPos[v]=w}else for(n=0;n<b;++n)q=3*n,t=q+1,v=q+2,c=this.prevMesh.uncompressedPos[q],h=this.prevMesh.uncompressedPos[t],w=this.prevMesh.uncompressedPos[v],y=h-this.prevPrevMesh.uncompressedPos[t],z=w-this.prevPrevMesh.uncompressedPos[v],c+=c-this.prevPrevMesh.uncompressedPos[q],h+=y,w+=z,y=x[q]*p+l[0],z=x[t]*u+l[1],A=x[v]*r+l[2],c+=y,h+=z,w+=A,e.uncompressedPos[q]=c,e.uncompressedPos[t]=h,e.uncompressedPos[v]=w;k.bindBuffer(k.ARRAY_BUFFER,a);k.bufferData(k.ARRAY_BUFFER,e.uncompressedPos,
k.DYNAMIC_DRAW)}if(f&&g.compressedNormals)if(this.fileInfo.octEncodedNormals){b=g.compressedNormals.length;a=new Float32Array(3*b);e=Math.abs;l=this._clamp;for(n=0;n<b;++n)c=g.compressedNormals[2*n],h=g.compressedNormals[2*n+1],c=-1+.0078125*c,h=-1+.0078125*h,w=1-e(c)-e(h),p=l(-w,0,1),c+=0<=c?-p:p,h+=0<=h?-p:p,p=1/Math.sqrt(c*c+h*h+w*w),a[3*n]=c*p,a[3*n+1]=h*p,a[3*n+2]=w*p;k.bindBuffer(k.ARRAY_BUFFER,f);k.bufferData(k.ARRAY_BUFFER,a,k.DYNAMIC_DRAW)}else k.bindBuffer(k.ARRAY_BUFFER,f),k.bufferData(k.ARRAY_BUFFER,
g.compressedNormals,k.DYNAMIC_DRAW);k.bindBuffer(k.ARRAY_BUFFER,d);k.bindBuffer(k.ELEMENT_ARRAY_BUFFER,m);return!0};HoloVideoObject.prototype._clamp=function(a,c,b){return a<c?c:a>b?b:a};
HoloVideoObject.prototype._onJsonLoaded=function(a){this._logInfo("got json");var c=this.json=JSON.parse(a);this.minBuffers=Math.min(this.openOptions.minBuffers,this.json.buffers.length-1);this.minVideos=Math.min(2,this.json.extensions[HoloVideoObject._extName].timeline.length);this.buffers=[null,null,null];0==this.videoElements.length&&(this.videoElements=[document.createElement("video")]);this.videoElements[0].setAttribute("playsinline","playsinline");this.videoElements[0].volume=this.audioVolume;
this.freeVideoElements.push(0);for(a=0;a<Math.min(this.openOptions.maxBuffers,this.json.buffers.length-1);++a)this.freeArrayBuffers.push(a);this._loadNextVideo();this._loadNextBuffer();this.currentBufferIndex=0;var b=this.json.accessors,f=this.json.meshes.length,e=this.buffers,g=this,d=function(){var n=c.bufferViews,h=c.buffers;if(this.primitives[0].extensions[HoloVideoObject._extName].attributes.POSITION){var l=n[this.indices.bufferView];if(void 0==h[l.buffer].arrayBufferIndex||e[h[l.buffer].arrayBufferIndex].bufferIndex!=
l.buffer)return g._logInfo("buffer for frame "+this.frameIndex+" not downloaded yet: "+h[l.buffer].uri),!1;l=n[this.compressedPos.bufferView];if(void 0==h[l.buffer].arrayBufferIndex||e[h[l.buffer].arrayBufferIndex].bufferIndex!=l.buffer)return g._logInfo("buffer for frame "+this.frameIndex+" not downloaded yet: "+h[l.buffer].uri),!1;l=n[this.compressedUVs.bufferView];if(void 0==h[l.buffer].arrayBufferIndex||e[h[l.buffer].arrayBufferIndex].bufferIndex!=l.buffer)return g._logInfo("buffer for frame "+
this.frameIndex+" not downloaded yet: "+h[l.buffer].uri),!1}else if(l=n[this.deltas.bufferView],void 0==h[l.buffer].arrayBufferIndex||e[h[l.buffer].arrayBufferIndex].bufferIndex!=l.buffer)return g._logInfo("buffer for frame "+this.frameIndex+" not downloaded yet: "+h[l.buffer].uri),!1;return this.compressedNormals&&(n=n[this.compressedNormals.bufferView],void 0==h[n.buffer].arrayBufferIndex||e[h[n.buffer].arrayBufferIndex].bufferIndex!=n.buffer)?(g._logInfo("buffer for frame "+this.frameIndex+" not downloaded yet: "+
h[n.buffer].uri),!1):!0};for(a=0;a<f;++a){var k=this.json.meshes[a];k.frameIndex=a;k.ensureBuffers=d;var m=k.primitives[0].extensions[HoloVideoObject._extName].attributes;m.POSITION?(k.indices=b[k.primitives[0].extensions[HoloVideoObject._extName].indices],k.compressedUVs=b[m.TEXCOORD_0],k.compressedPos=b[m.POSITION]):k.deltas=b[m._DELTA];null!=m.NORMAL&&(this.fileInfo.haveNormals=!0,k.compressedNormals=b[m.NORMAL],"VEC2"==k.compressedNormals.type&&(this.fileInfo.octEncodedNormals=!0));this.meshFrames.push(k)}a=
this.json.images[1].extensions[HoloVideoObject._extName];this.fileInfo.videoWidth=a.width;this.fileInfo.videoHeight=a.height;b=this.json.extensions[HoloVideoObject._extName];this.fileInfo.maxVertexCount=b.maxVertexCount;this.fileInfo.maxIndexCount=b.maxIndexCount;this.fileInfo.boundingBox={min:b.boundingMin,max:b.boundingMax};if(this.onLoaded)this.onLoaded(this.fileInfo);if(this.outputBuffers){f=this.gl;d=f.getParameter(f.ARRAY_BUFFER_BINDING);for(a=0;3>a;++a)f.bindBuffer(f.ARRAY_BUFFER,this.outputBuffers[a]),
f.bufferData(f.ARRAY_BUFFER,12*b.maxVertexCount,f.STREAM_COPY);f.bindBuffer(f.ARRAY_BUFFER,d)}};HoloVideoObject.prototype._getChromeVersion=function(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1};
HoloVideoObject.prototype._getIOSVersion=function(){var a=window.navigator.userAgent;if(0<a.indexOf("iPhone")||0<a.indexOf("iPad"))if(a=a.match(/OS (\d+)_(\d+)_?(\d+)?/))return{major:parseInt(a[1]||0,10),minor:parseInt(a[2]||0,10),patch:parseInt(a[3]||0,10)};return!1};HoloVideoObject.prototype._logDebug=function(a,c){3<=this.logLevel&&console.log("["+this.id+"] "+a)};HoloVideoObject.prototype._logInfo=function(a,c){(2<=this.logLevel||c)&&console.log("["+this.id+"] "+a)};
HoloVideoObject.prototype._logWarning=function(a){1<=this.logLevel&&console.log("["+this.id+"] "+a)};HoloVideoObject.prototype._logError=function(a){0<=this.logLevel&&console.log("["+this.id+"] "+a)};
HoloVideoObject.prototype._initializeWebGLResources=function(a){var c={},b=a.getParameter(a.VERSION);c.webgl2=-1!=b.indexOf("WebGL 2.");c.badTF=!1;this.isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);this.iOSVersion=this._getIOSVersion();navigator.userAgent.includes("Mobile")&&"iPhone"!=navigator.platform&&"iPad"!=navigator.platform&&(this.isSafari=!1);if(b=a.getExtension("WEBGL_debug_renderer_info"))c.vendor=a.getParameter(b.UNMASKED_VENDOR_WEBGL),c.renderer=a.getParameter(b.UNMASKED_RENDERER_WEBGL),
c.isSafari=this.isSafari,c.iOSVersion=this.iOSVersion,-1!=c.renderer.indexOf("Mali")&&(c.badTF=!0);b=JSON.stringify(c,null,4);console.log(b);this.caps=c;this.fbo1=a.createFramebuffer();this.caps.webgl2?(this.caps.badTF||this._setupTransformFeedback(),this.createOptions.disableAsyncDecode?this.textures=[null]:(this.fbo2=a.createFramebuffer(),this.textures=Array(this.createOptions.numAsyncFrames),this.pixelBuffers=Array(this.createOptions.numAsyncFrames),this.readFences=Array(this.createOptions.numAsyncFrames),
this.nextPbo=0)):this.textures=[null];c=a.getParameter(a.TEXTURE_BINDING_2D);for(b=0;b<this.textures.length;++b)this.textures[b]=a.createTexture(),a.bindTexture(a.TEXTURE_2D,this.textures[b]),a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE),a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE),a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR),a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);a.bindTexture(a.TEXTURE_2D,c)};
HoloVideoObject.prototype._releaseWebGLResources=function(a){if(this.caps.webgl2&&!this.caps.badTF){a.deleteBuffer(this.deltasBuf);for(var c=0;3>c;++c)a.deleteBuffer(this.outputBuffers[c]),this.outputBuffers[c]=null,a.deleteTransformFeedback(this.transformFeedbacks[c]),this.transformFeedbacks[c]=null,a.deleteVertexArray(this.vaos[c]),this.vaos[c]=null;a.deleteTransformFeedback(this.normalsTF);this.normalsTF=null;a.deleteVertexArray(this.normalsVao);this.normalsVao=null;a.deleteProgram(this.tfShader);
this.tfShader=null;a.deleteProgram(this.octNormalsShader);this.octNormalsShader=null}if(this.pixelBuffers)for(c=0;c<this.pixelBuffers.length;++c)a.deleteBuffer(this.pixelBuffers[c]),this.pixelBuffers[c]=null;if(this.readFences)for(c=0;c<this.readFences.length;++c)a.deleteSync(this.readFences[c]),this.readFences[c]=null;for(c=this.nextPbo=0;c<this.textures.length;++c)a.deleteTexture(this.textures[c]);this.fbo1&&(a.deleteFramebuffer(this.fbo1),this.fbo1=null);this.fbo2&&(a.deleteFramebuffer(this.fbo2),
this.fbo2=null)};HoloVideoObject.prototype.getLoadProgress=function(){return void 0==this.minBuffers?0:this.state>=HoloVideoObject.States.Opened?1:(this.buffersLoaded+this.videosLoaded)/(this.minBuffers+this.minVideos)};HoloVideoObject.prototype.setBuffers=function(a,c,b,f,e){var g={};g.posBuf=a;g.indexBuf=c;g.uvBuf=b;g.norBuf=f;g.tex=e;this.clientBuffers=g};
HoloVideoObject.prototype.updateToLastKeyframe=function(){-1!=this.lastKeyframe&&(this.frameIndex=this.lastKeyframe-1,this.prevPrevMesh=this.prevMesh=this.curMesh=null)};
HoloVideoObject.prototype._loadFallbackFrame=function(){if(this.json&&this.fallbackFrameBuffer){if(!this.fallbackTextureImage){this.fallbackTextureImage=new Image;var a=this.json.bufferViews[this.json.images[0].bufferView];this.fallbackTextureImage.src="data:image/jpeg;base64,"+function(d){for(var k="",m,n,h,l,p,u,r=0;r<d.length;)m=d[r++],n=r<d.length?d[r++]:Number.NaN,h=r<d.length?d[r++]:Number.NaN,l=m>>2,m=(m&3)<<4|n>>4,p=(n&15)<<2|h>>6,u=h&63,isNaN(n)?p=u=64:isNaN(h)&&(u=64),k+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(l)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(p)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(u);return k}(new Uint8Array(this.fallbackFrameBuffer,a.byteOffset,a.byteLength));this.fallbackTextureImage.onload=function(){this._logInfo("fallback image loaded");this.fallbackTextureImage.loaded=!0}.bind(this)}if(this.fallbackTextureImage&&this.fallbackTextureImage.loaded&&
!this.filledFallbackFrame&&this.clientBuffers&&this.clientBuffers.posBuf){a=this.gl;var c=this.json.meshes[0].primitives[0],b=a.getParameter(a.ARRAY_BUFFER_BINDING),f=a.getParameter(a.ELEMENT_ARRAY_BUFFER_BINDING),e=this.json.accessors[c.attributes.POSITION],g=this.json.bufferViews[e.bufferView];a.bindBuffer(a.ARRAY_BUFFER,this.clientBuffers.posBuf);a.bufferData(a.ARRAY_BUFFER,new Float32Array(this.fallbackFrameBuffer,g.byteOffset+e.byteOffset,3*e.count),a.STATIC_DRAW);this.clientBuffers.norBuf&&
this.fileInfo.haveNormals&&(e=this.json.accessors[c.attributes.NORMAL],g=this.json.bufferViews[e.bufferView],a.bindBuffer(a.ARRAY_BUFFER,this.clientBuffers.norBuf),a.bufferData(a.ARRAY_BUFFER,new Float32Array(this.fallbackFrameBuffer,g.byteOffset+e.byteOffset,3*e.count),a.STATIC_DRAW));e=this.json.accessors[c.attributes.TEXCOORD_0];g=this.json.bufferViews[e.bufferView];a.bindBuffer(a.ARRAY_BUFFER,this.clientBuffers.uvBuf);a.bufferData(a.ARRAY_BUFFER,new Uint16Array(this.fallbackFrameBuffer,g.byteOffset+
e.byteOffset,2*e.count),a.STATIC_DRAW);e=this.json.accessors[c.indices];g=this.json.bufferViews[e.bufferView];a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,this.clientBuffers.indexBuf);a.bufferData(a.ELEMENT_ARRAY_BUFFER,new Uint16Array(this.fallbackFrameBuffer,g.byteOffset+e.byteOffset,e.count),a.STATIC_DRAW);a.bindBuffer(a.ARRAY_BUFFER,b);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,f);a.pixelStorei(a.PACK_ALIGNMENT,4);a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!1);a.pixelStorei(a.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);b=a.getParameter(a.TEXTURE_BINDING_2D);
a.bindTexture(a.TEXTURE_2D,this.clientBuffers.tex);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,this.fallbackTextureImage);a.bindTexture(a.TEXTURE_2D,b);this.currentFrameInfo.primCount=e.count;e=this.json.accessors[c.extensions[HoloVideoObject._extName].attributes.POSITION];a=e.extensions[HoloVideoObject._extName].decodeMax;this.currentFrameInfo.bboxMin=e.extensions[HoloVideoObject._extName].decodeMin;this.currentFrameInfo.bboxMax=a;this.filledFallbackFrame=!0}return this.filledFallbackFrame}};
HoloVideoObject.prototype.updateBuffers=function(){if(this.contextLost)return!1;if(!this.filledFallbackFrame)return this._loadFallbackFrame();var a=this.json.images[this.json.extensions[HoloVideoObject._extName].timeline[this.currentVideoIndex].image],c=a.video;if(c&&c.playing&&!this.suspended){var b=window.performance.now();if(20>b-this.lastUpdate)return!1;this.lastVideoTime=1E3*c.currentTime;this.lastUpdate=b;b=this.gl;this.watermarkPixels||(this.watermarkPixels=new Uint8Array(4*a.extensions[HoloVideoObject._extName].width));
var f=-1,e=b.getParameter(b.FRAMEBUFFER_BINDING),g=b.getParameter(b.TEXTURE_BINDING_2D),d=this.caps.webgl2&&!this.createOptions.disableAsyncDecode;if(d){var k=(this.nextPbo+1)%this.pixelBuffers.length;if(null!=this.readFences[k]){b.getSyncParameter(this.readFences[k],b.SYNC_STATUS);b.deleteSync(this.readFences[k]);this.readFences[k]=null;b.bindBuffer(b.PIXEL_PACK_BUFFER,this.pixelBuffers[k]);b.getBufferSubData(b.PIXEL_PACK_BUFFER,0,this.watermarkPixels,0,this.watermarkPixels.byteLength);var m=4*a.extensions[HoloVideoObject._extName].blockSize;
for(a=f=0;16>a;++a)if(128<this.watermarkPixels[m*a]||128<this.watermarkPixels[m*a+4])f+=1<<a}this.pixelBuffers[this.nextPbo]||(this.pixelBuffers[this.nextPbo]=b.createBuffer(),b.bindBuffer(b.PIXEL_PACK_BUFFER,this.pixelBuffers[this.nextPbo]),b.bufferData(b.PIXEL_PACK_BUFFER,this.watermarkPixels.byteLength,b.DYNAMIC_READ));b.pixelStorei(b.PACK_ALIGNMENT,4);b.pixelStorei(b.UNPACK_FLIP_Y_WEBGL,!1);b.pixelStorei(b.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);b.bindTexture(b.TEXTURE_2D,this.textures[this.nextPbo]);
b.texImage2D(b.TEXTURE_2D,0,b.RGBA,b.RGBA,b.UNSIGNED_BYTE,c);b.bindFramebuffer(b.FRAMEBUFFER,this.fbo1);b.framebufferTexture2D(b.FRAMEBUFFER,b.COLOR_ATTACHMENT0,b.TEXTURE_2D,this.textures[this.nextPbo],0);b.bindBuffer(b.PIXEL_PACK_BUFFER,this.pixelBuffers[this.nextPbo]);b.readPixels(0,0,this.watermarkPixels.byteLength/4,1,b.RGBA,b.UNSIGNED_BYTE,0);b.bindFramebuffer(b.FRAMEBUFFER,null);this.readFences[this.nextPbo]=b.fenceSync(b.SYNC_GPU_COMMANDS_COMPLETE,0);this.nextPbo=(this.nextPbo+1)%this.pixelBuffers.length}else if(b.pixelStorei(b.PACK_ALIGNMENT,
4),b.pixelStorei(b.UNPACK_FLIP_Y_WEBGL,!1),b.pixelStorei(b.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1),b.bindTexture(b.TEXTURE_2D,this.textures[0]),b.texImage2D(b.TEXTURE_2D,0,b.RGBA,b.RGBA,b.UNSIGNED_BYTE,c),m=b.getError(),m==b.NO_ERROR){b.bindFramebuffer(b.FRAMEBUFFER,this.fbo1);b.framebufferTexture2D(b.FRAMEBUFFER,b.COLOR_ATTACHMENT0,b.TEXTURE_2D,this.textures[0],0);b.readPixels(0,0,this.watermarkPixels.byteLength/4,1,b.RGBA,b.UNSIGNED_BYTE,this.watermarkPixels);m=4*a.extensions[HoloVideoObject._extName].blockSize;
for(a=f=0;16>a;++a)if(128<this.watermarkPixels[m*a]||128<this.watermarkPixels[m*a+4])f+=1<<a;m=!0;if(0==f&&f<this.lastVideoSampleIndex){for(a=0;a<this.watermarkPixels.byteLength;++a)if(0!=this.watermarkPixels[a]){m=!1;break}if(m)return this._logWarning("dropping empty/black video frame"),this.currentFrameInfo.primCount=0,!0}}else this._logWarning("webgl error: "+m+" skipping video texture read");if(-1<f&&(null==this.curMesh||this.curMesh.frameIndex!=f))if(this._logDebug("videoSampleIndex -> "+f),
this.meshFrames[f].ensureBuffers()){f<this.lastVideoSampleIndex&&(this.frameIndex=-1,this._updateMesh(this.clientBuffers.posBuf,this.clientBuffers.uvBuf,this.clientBuffers.indexBuf,this.clientBuffers.norBuf),this._logInfo("loop detected, videoSampleIndex = "+f+", curMesh.frameIndex = "+this.curMesh.frameIndex));for(;(null==this.curMesh||this.curMesh.frameIndex<f)&&this._updateMesh(this.clientBuffers.posBuf,this.clientBuffers.uvBuf,this.clientBuffers.indexBuf,this.clientBuffers.norBuf););this._logDebug("updated to frame index = "+
f);this.curMesh.frameIndex==f&&(a=c.videoWidth,c=c.videoHeight,d?(b.bindFramebuffer(b.READ_FRAMEBUFFER,this.fbo1),b.framebufferTexture2D(b.READ_FRAMEBUFFER,b.COLOR_ATTACHMENT0,b.TEXTURE_2D,this.textures[k],0),b.readBuffer(b.COLOR_ATTACHMENT0),b.bindFramebuffer(b.DRAW_FRAMEBUFFER,this.fbo2),b.framebufferTexture2D(b.DRAW_FRAMEBUFFER,b.COLOR_ATTACHMENT0,b.TEXTURE_2D,this.clientBuffers.tex,0),b.drawBuffers([b.COLOR_ATTACHMENT0]),b.checkFramebufferStatus(b.READ_FRAMEBUFFER),b.checkFramebufferStatus(b.DRAW_FRAMEBUFFER),
b.blitFramebuffer(0,0,a,c,0,0,a,c,b.COLOR_BUFFER_BIT,b.NEAREST)):(b.bindTexture(b.TEXTURE_2D,this.clientBuffers.tex),b.copyTexSubImage2D(b.TEXTURE_2D,0,0,0,0,0,a,c)));this.curMesh&&this.curMesh.frameIndex!=f&&this._logInfo("texture ("+f+") <-> mesh ("+this.curMesh.frameIndex+") mismatch");this.lastVideoSampleIndex=f}else this._logWarning("ran out of mesh data, suspending video "+c.mp4Name),c.pause(),this.needMeshData=this.suspended=!0,this.pendingBufferDownload||this._loadNextBuffer();b.bindFramebuffer(b.FRAMEBUFFER,
e);b.bindTexture(b.TEXTURE_2D,g)}if(this.curMesh){this.currentFrameInfo.primCount=this.curMesh.indexCount;this.currentFrameInfo.frameIndex=this.curMesh.frameIndex;if(this.onUpdateCurrentFrame)this.onUpdateCurrentFrame(this.curMesh.frameIndex);return!0}return!1};
HoloVideoObject.prototype.close=function(){this.httpRequest&&(this.httpRequest.abort(),this.httpRequest=null);this.dashPlayer&&this.dashPlayer.reset();for(var a=0;a<this.videoElements.length;++a)this.videoElements[a].pause(),this.videoElements[a].removeAttribute("src");this.state=HoloVideoObject.States.Closed};HoloVideoObject.prototype.pause=function(){0<this.videoElements.length&&this.videoElements[this.currentVideoIndex]&&(this.videoElements[this.currentVideoIndex].pause(),this.state=HoloVideoObject.States.Paused)};
HoloVideoObject.prototype.setAudioVolume=function(a){this.audioVolume=a;this.videoElements[this.currentVideoIndex].volume=a};HoloVideoObject.prototype.setAutoLooping=function(a){this.openOptions.autoloop=a;this.videoElements[this.currentVideoIndex].loop=a};HoloVideoObject.prototype.setAudioEnabled=function(a){this.videoElements[this.currentVideoIndex].muted=!a};HoloVideoObject.prototype.audioEnabled=function(){return!this.videoElements[this.currentVideoIndex].muted};
HoloVideoObject.prototype.play=function(){var a=this;this.isSafari&&this.videoElements[this.currentVideoIndex].pause();var c=this.videoElements[this.currentVideoIndex].play();void 0!==c&&c.then(function(b){a.state=HoloVideoObject.States.Playing}).catch(function(b){a._logInfo("play prevented: "+b)})};
HoloVideoObject.prototype.open=function(a,c){this.state>=HoloVideoObject.States.Opening&&this.close();this.state=HoloVideoObject.States.Opening;this.urlRoot=a.substring(0,a.lastIndexOf("/")+1);this.meshFrames=[];this.videosLoaded=this.buffersLoaded=0;this.freeArrayBuffers=[];this.freeVideoElements=[];this.buffers=[];void 0===this.videoElements&&(this.videoElements=[]);this.nextBufferLoadIndex=this.nextVideoLoadIndex=0;this.videoState=HoloVideoObject.VideoStates.Undefined;this.currentFrameInfo={primCount:0};
this.currentVideoIndex=0;this.currentBufferIndex=-1;this.lastUpdate=this.lastVideoTime=0;this.json=null;this.fileInfo={haveNormals:!1,octEncodedNormals:!1};this.openOptions=c?c:{};this.openOptions.minBuffers||(this.openOptions.minBuffers=2);this.openOptions.maxBuffers||(this.openOptions.maxBuffers=3);if(this.readFences)for(c=0;c<this.readFences.length;++c)this.readFences[c]&&(this.gl.deleteSync(this.readFences[c]),this.readFences[c]=null);this.nextPbo=0;this.prevPrevMesh=this.prevMesh=this.curMesh=
null;this.lastVideoSampleIndex=this.lastKeyframe=this.frameIndex=-1;this.filledFallbackFrame=!1;this.fallbackTextureImage=this.fallbackFrameBuffer=null;this.eos=!1;this._loadJSON(a,this._onJsonLoaded.bind(this))};
"undefined"!=typeof THREE&&(HoloVideoObjectThreeJS=function(a,c,b,f){var e=new HoloVideoObject(a.getContext(),b);this.hvo=e;this.renderer=a;e.onEndOfStream=this._hvoOnEndOfStream.bind(this);e.onUpdateCurrentFrame=f;e.onLoaded=function(d){this.fileInfo=d;var k=d.haveNormals,m=new THREE.MeshBasicMaterial({map:null,transparent:!1,side:THREE.DoubleSide}),n=new THREE.MeshLambertMaterial({map:null,transparent:!1,side:THREE.DoubleSide});if(this.mesh)d=k?n:m,d.map=this.mesh.material.map,this.mesh.material=
d;else{var h=a.getContext(),l=new THREE.BufferGeometry;l.boundingSphere=new THREE.Sphere;l.boundingSphere.set(new THREE.Vector3,Infinity);l.boundingBox=new THREE.Box3;l.boundingBox.set(new THREE.Vector3(-Infinity,-Infinity,-Infinity),new THREE.Vector3(Infinity,Infinity,Infinity));var p=h.createBuffer(),u=120<=THREE.REVISION?new THREE.GLBufferAttribute(p,h.FLOAT,3,0):new THREE.GLBufferAttribute(h,p,h.FLOAT,3,0);l.setAttribute("position",u);u=null;if(k){u=h.createBuffer();var r=120<=THREE.REVISION?
new THREE.GLBufferAttribute(u,h.FLOAT,3,0):new THREE.GLBufferAttribute(h,u,h.FLOAT,3,0);l.setAttribute("normal",r)}r=h.createBuffer();var q=120<=THREE.REVISION?new THREE.GLBufferAttribute(r,h.UNSIGNED_SHORT,2,0):new THREE.GLBufferAttribute(h,r,h.UNSIGNED_SHORT,2,0);q.normalized=!0;l.setAttribute("uv",q);q=h.createBuffer();var t=120<=THREE.REVISION?new THREE.GLBufferAttribute(q,h.UNSIGNED_SHORT,2,0):new THREE.GLBufferAttribute(h,q,h.UNSIGNED_SHORT,2,0);l.setIndex(t);var v=new THREE.Texture;v.encoding=
THREE.sRGBEncoding;t=a.properties.get(v);t.__webglTexture=h.createTexture();var x=h.getParameter(h.TEXTURE_BINDING_2D);h.bindTexture(h.TEXTURE_2D,t.__webglTexture);h.texImage2D(h.TEXTURE_2D,0,h.RGBA,d.videoWidth,d.videoHeight,0,h.RGBA,h.UNSIGNED_BYTE,null);h.texParameteri(h.TEXTURE_2D,h.TEXTURE_WRAP_S,h.CLAMP_TO_EDGE);h.texParameteri(h.TEXTURE_2D,h.TEXTURE_WRAP_T,h.CLAMP_TO_EDGE);h.texParameteri(h.TEXTURE_2D,h.TEXTURE_MIN_FILTER,h.LINEAR);h.texParameteri(h.TEXTURE_2D,h.TEXTURE_MAG_FILTER,h.LINEAR);
h.bindTexture(h.TEXTURE_2D,x);d=k?n:m;d.map=v;d=new THREE.Mesh(l,d);d.scale.x=.001;d.scale.y=.001;d.scale.z=.001;e.setBuffers(p,q,r,u,t.__webglTexture);this.mesh=d;this.bufferGeometry=l}this.state=this.hvo.state;c(this.mesh)}.bind(this);var g=a.getContext();b=g.canvas;b.addEventListener("webglcontextlost",function(d){this.mesh&&g.deleteTexture(this.mesh.material.map.__webglTexture)}.bind(this),!1);b.addEventListener("webglcontextrestored",function(d){if(this.mesh){var k=this.mesh.geometry,m=this.renderer;
m.geometries.update(k);var n=null,h;d=k.attributes.position.buffer;if(h=k.attributes.normal)n=h.buffer;h=k.attributes.uv.buffer;k=k.getIndex().buffer;var l=new THREE.Texture;l.encoding=THREE.sRGBEncoding;m=m.properties.get(l);m.__webglTexture=g.createTexture();var p=g.getParameter(g.TEXTURE_BINDING_2D);g.bindTexture(g.TEXTURE_2D,m.__webglTexture);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,this.fileInfo.videoWidth,this.fileInfo.videoHeight,0,g.RGBA,g.UNSIGNED_BYTE,null);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,
g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.bindTexture(g.TEXTURE_2D,p);this.mesh.material.map=l;this.hvo.setBuffers(d,k,h,n,m.__webglTexture);this.hvo.updateToLastKeyframe();this.bufferGeometry.index.count=0}}.bind(this),!1)},HoloVideoObjectThreeJS.prototype._hvoOnEndOfStream=function(a){if(this.onEndOfStream)this.onEndOfStream(this)},HoloVideoObjectThreeJS.prototype.open=
function(a,c){this.state>HoloVideoObject.States.Empty&&this.close();this.hvo.open(a,c);this.state=this.hvo.state},HoloVideoObjectThreeJS.prototype.update=function(){this.hvo&&this.mesh&&(this.state=this.hvo.state);if(this.hvo.updateBuffers()){var a=this.hvo.currentFrameInfo.bboxMin,c=this.hvo.currentFrameInfo.bboxMax,b=this.bufferGeometry;b.boundingBox.min.x=a[0];b.boundingBox.min.y=a[1];b.boundingBox.min.z=a[2];b.boundingBox.max.x=c[0];b.boundingBox.max.y=c[1];b.boundingBox.max.z=c[2];b.boundingBox.getCenter(b.boundingSphere.center);
b.boundingSphere.radius=.5*Math.max(c[0]-a[0],c[1]-a[1],c[2]-a[2]);b.index.count=this.hvo.currentFrameInfo.primCount}},HoloVideoObjectThreeJS.prototype.rewind=function(){this.hvo.rewind()},HoloVideoObjectThreeJS.prototype.play=function(){this.hvo.state==HoloVideoObject.States.Opening?this.hvo.forceLoad():this.hvo.state>=HoloVideoObject.States.Opened&&this.hvo.state!=HoloVideoObject.States.Playing&&this.hvo.play()},HoloVideoObjectThreeJS.prototype.close=function(){this.bufferGeometry&&(this.bufferGeometry.index.count=
0);this.hvo.close()},HoloVideoObjectThreeJS.prototype.pause=function(){this.hvo.pause()},HoloVideoObjectThreeJS.prototype.setLogLevel=function(a){this.hvo.logLevel=a},HoloVideoObjectThreeJS.prototype.setAudioEnabled=function(a){this.hvo.setAudioEnabled(a)},HoloVideoObjectThreeJS.prototype.audioEnabled=function(){return this.hvo.audioEnabled()},HoloVideoObjectThreeJS.prototype.setAudioVolume=function(a){this.hvo.setAudioVolume(a)},HoloVideoObjectThreeJS.prototype.setAutoLooping=function(a){this.hvo.setAutoLooping(a)});
HoloVideoObject._instanceCounter=0;HoloVideoObject.States={Closed:-1,Empty:0,Opening:1,Opened:2,Playing:3,Paused:4};HoloVideoObject.StreamMode={Automatic:0,MP4:1,HLS:2,Dash:3};HoloVideoObject.VideoStates={Undefined:0,CanPlay:1,CanPlayThrough:2,Waiting:3,Suspended:4,Stalled:5,Playing:6};HoloVideoObject._extName="HCAP_holovideo";HoloVideoObject.Version={};HoloVideoObject.Version.Major=1;HoloVideoObject.Version.Minor=2;HoloVideoObject.Version.Patch=9;
HoloVideoObject.Version.String=HoloVideoObject.Version.Major+"."+HoloVideoObject.Version.Minor+"."+HoloVideoObject.Version.Patch;
